@ | vagrant gatling auto restart when error
teracyhq-incubator/teracy-dev-v05-compat pull request #17
Opened 2018-12-09 18:53 UTC by hieptranquoc

connect #10 
please check this PR! Thank you!

2018-12-10 03:29 UTC, datphan reviewed
@hieptranquoc pls check my comment

2018-12-10 03:29 UTC, datphan commented on lib/teracy-dev-v05-compat/trigger/rsync_trigger.rb
> +        return unless TeracyDev::Util.true?(rsync_exists)
this look cleaner for me

```
rsync_exists = synced_folders_settings.find { |x| x['type'] == 'rsync' } # or x[:type]

return if rsync_exists.nil?
```

2018-12-10 03:29 UTC, datphan commented on lib/teracy-dev-v05-compat/trigger/rsync_trigger.rb
> +        end
```
return if !gatling_rsync? # or unless gatling_rsync?

# To Ensure gatling-rsync don't run on start up
config.gatling.rsync_on_startup = false

....
```

2018-12-10 03:29 UTC, datphan commented on lib/teracy-dev-v05-compat/trigger/rsync_trigger.rb
> +        # TODO (hieptq) : should make 'vagrant rsync-auto' restart when crashed
should remove "TODO.."

2018-12-10 03:29 UTC, datphan commented on lib/teracy-dev-v05-compat/trigger/rsync_trigger.rb
> +      end
```
def gatling_rsync_installed?
  return TeracyDev::Plugin.installed?('vagrant-gatling-rsync')
end
```

2018-12-10 08:45 UTC, hieptranquoc commented
@datphan applied your comment! Thank you

2018-12-10 08:49 UTC, hieptranquoc commented
Please check with step:
1. create `guest_test.sh` in workspace
```
#!/bin/bash
for i in {0..10000}
do
    touch $(pwd)/test.yaml
    echo "file created test.yaml"
    rm -rf $(pwd)/test.yaml
    echo "file deleted test.yaml"
done
```

2. create `host_test.sh` in workspace
```
#!/bin/bash
for i in {0..10000}
do
    touch $(pwd)/test.yaml
    echo "file created test.yaml"
    sleep 2
    rm -rf $(pwd)/test.yaml
    echo "file deleted test.yaml"
done
```
3. vagrant up
4. open 1 terminal tab, and run `vagrant ssh` , and then run `workspace/guest_test.sh`
5 open another terminal tab, and run `workspace/host_test.sh`

2018-12-11 05:47 UTC, datphan reviewed
@hieptranquoc  pls check my comment
vagrant 2.1.2 does not working, but vagrant 2.2.2 does

2018-12-11 05:47 UTC, datphan commented on lib/teracy-dev-v05-compat/trigger/rsync_trigger.rb
> +              retry
should have a message to tell user about restart the rsync
```
puts "rsync crashed, retrying..."
```

2018-12-11 08:45 UTC, hieptranquoc commented
@datphan applied your comment! Thank you. Please check again!

2018-12-11 08:47 UTC, datphan submitted a review, later dismissed

2018-12-11 09:05 UTC, hoatle requested changes
@hieptranquoc pls check my comments

2018-12-11 09:05 UTC, hoatle commented on lib/teracy-dev-v05-compat/trigger/rsync_trigger.rb
> +require 'teracy-dev/config/configurator'
let's rename and move the `rsync_trigger.rb` to `lib/config/gatling-rsync-recovery.rb`
```ruby
GatlingRsyncRecovery < Configurator
```

2018-12-11 09:08 UTC, hoatle commented
@datphan's comments on this:

```
@hieptranquoc pls check my comment
vagrant 2.1.2 does not working, but vagrant 2.2.2 does
```

@hieptranquoc make sure the changes should work with vagrant >= 2.1

2018-12-11 10:07 UTC, hieptranquoc commented
@hoatle I've updated! please check this PR again! Thank you!

2018-12-11 10:09 UTC, hoatle reviewed
@hieptranquoc LGTM, need to use logger.info instead of puts. need @phuonglm's approval.

2018-12-11 10:09 UTC, hoatle commented on lib/teracy-dev-v05-compat/config/gatling_rsync_recovery.rb
> +              puts 'rsync crashed, retrying...'
use @logger.info here

2018-12-11 10:15 UTC, hieptranquoc commented
I've applied your comment! Thank you!

2018-12-12 01:43 UTC, phuonglm commented
```
==> iorad.local: Doing an initial rsync...
==> iorad.local: Rsyncing folder: /home/phuonglm/Projects/teracy/dev/workspace/ => /home/vagrant/workspace
==> iorad.local:   - Exclude: [".vagrant/", ".git", ".idea", ".#*", "node_modules", "bower_components", "iorad/node/static/downloadtutorials/html", "iorad/.tmp", "iorad/app/scripts/base/templates/dist", "iorad/app/scripts/editor/templates/dist", "iorad/app/scripts/editor/workers/dist", "iorad/app/scripts/player/templates/dist", "iorad/app/scripts/player/workers/dist", "iorad/node/static/_dist", "iorad/node/static/dist", "iorad/node/static/assets/css", "iorad/node/static/webstart", "iorad/node/static/data", "iorad/node/static/assets/avatars", "iorad/node/webpack-assets.json", "target", ".backup-info", "iorad/helm-charts", "iorad/scripts", "iorad/.cache"]
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

find /home/vagrant/workspace -path /home/vagrant/workspace/.git -prune -o -path /home/vagrant/workspace/.idea -prune -o -path /home/vagrant/workspace/.\#\* -prune -o -path /home/vagrant/workspace/node_modules -prune -o -path /home/vagrant/workspace/bower_components -prune -o -path /home/vagrant/workspace/iorad/node/static/downloadtutorials/html -prune -o -path /home/vagrant/workspace/iorad/.tmp -prune -o -path /home/vagrant/workspace/iorad/app/scripts/base/templates/dist -prune -o -path /home/vagrant/workspace/iorad/app/scripts/editor/templates/dist -prune -o -path /home/vagrant/workspace/iorad/app/scripts/editor/workers/dist -prune -o -path /home/vagrant/workspace/iorad/app/scripts/player/templates/dist -prune -o -path /home/vagrant/workspace/iorad/app/scripts/player/workers/dist -prune -o -path /home/vagrant/workspace/iorad/node/static/_dist -prune -o -path /home/vagrant/workspace/iorad/node/static/dist -prune -o -path /home/vagrant/workspace/iorad/node/static/assets/css -prune -o -path /home/vagrant/workspace/iorad/node/static/webstart -prune -o -path /home/vagrant/workspace/iorad/node/static/data -prune -o -path /home/vagrant/workspace/iorad/node/static/assets/avatars -prune -o -path /home/vagrant/workspace/iorad/node/webpack-assets.json -prune -o -path /home/vagrant/workspace/target -prune -o -path /home/vagrant/workspace/.backup-info -prune -o -path /home/vagrant/workspace/iorad/helm-charts -prune -o -path /home/vagrant/workspace/iorad/scripts -prune -o -path /home/vagrant/workspace/iorad/.cache -prune -o '!' -type l -a '(' ! -user vagrant -or ! -group vagrant ')' -exec chown vagrant:vagrant '{}' +

Stdout from the command:



Stderr from the command:

find: ‘/home/vagrant/workspace/iorad/.9577.yaml’: No such file or directory
chown: cannot access '/home/vagrant/workspace/iorad/.9577.yaml': No such file or directory

[TeracyDevEssential::Config::HostManager][WARN]: [["192.168.1.206 iorad.local", "192.168.1.206 iorad.local"], ["192.168.1.206 iorad.local", "192.168.1.206 iorad.local"]] are conflicted with each other, maybe you haven't clean the old VM setup, you can resolve this by go to the old setup repo then run: 'vagrant destroy' or 'vagrant halt && vagrant hostmanager' or you can open '/etc/hosts' and clean it manually.

==> iorad.local: Doing an initial rsync...
==> iorad.local: Rsyncing folder: /home/phuonglm/Projects/teracy/dev/workspace/ => /home/vagrant/workspace
==> iorad.local:   - Exclude: [".vagrant/", ".git", ".idea", ".#*", "node_modules", "bower_components", "iorad/node/static/downloadtutorials/html", "iorad/.tmp", "iorad/app/scripts/base/templates/dist", "iorad/app/scripts/editor/templates/dist", "iorad/app/scripts/editor/workers/dist", "iorad/app/scripts/player/templates/dist", "iorad/app/scripts/player/workers/dist", "iorad/node/static/_dist", "iorad/node/static/dist", "iorad/node/static/assets/css", "iorad/node/static/webstart", "iorad/node/static/data", "iorad/node/static/assets/avatars", "iorad/node/webpack-assets.json", "target", ".backup-info", "iorad/helm-charts", "iorad/scripts", "iorad/.cache"]
==> iorad.local: Watching: /home/phuonglm/Projects/teracy/dev/workspace
```
auto restart after crash, LGTM

2018-12-12 01:44 UTC, phuonglm approved these changes

2018-12-12 02:04 UTC, hoatle approved these changes

2018-12-12 02:05 UTC, merged