@ #11 | fix bug failed to sync created files from Linux host
teracyhq-incubator/teracy-dev-v05-compat pull request #21
Opened 2018-12-20 09:56 UTC by hieptranquoc

connect #11 
please check this PR! Thank you!

2018-12-20 10:01 UTC, hoatle requested changes
@hieptranquoc please check my comments.

2018-12-20 10:01 UTC, hoatle commented on lib/teracy-dev-v05-compat/config/rsync_recovery.rb
> +            @logger.warn("See more at: https://github.com/hashicorp/vagrant/issues/10460")
in this case, use `gatling-rsync-auto`

2018-12-20 10:10 UTC, hieptranquoc commented
@hoatle I applied your comment! Please check this PR again! Thank you!

2018-12-20 10:14 UTC, hoatle commented
need @phuonglm to review.

2019-01-22 09:11 UTC, closed without merging

2019-01-22 09:13 UTC, hieptranquoc commented
will be fixed when teracy-dev-essential v0.3.0 is released!